In [ ]:
# 2차원 -> 피타고라스정리...
# 차원이 높아지면 거리 뭘로 구하나 -> 유클리드거리
# kNN자체가 유클리드거리고 구하는 알고리즘

# 비행기 : 몇만단위, 게임 : 최대100, 아이스크림 : 최대2?
# 저대로 kNN하면 비행기만 크게 영향 끼칠 뿐 -> 동등하게 하려면
#       정규화 : 상수값 -> 비율로

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("./Users/teacher02/Jan26_1_MachineLearning/datingTestSet.txt", sep="\t", 
                names=["비행기", "게임", "아이스크림", "인기도"])

feature = df[["비행기", "게임", "아이스크림"]].to_numpy()
label = df["인기도"].to_numpy()

print(feature)
print(label)

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 ...
 [2.6575000e+04 1.0650102e+01 8.6662700e-01]
 [4.8111000e+04 9.1345280e+00 7.2804500e-01]
 [4.3757000e+04 7.8826010e+00 1.3324460e+00]]
['인기많음' '보통' '별로' '별로' '별로' '별로' '인기많음' '인기많음' '별로' '인기많음' '별로' '별로' '보통'
 '별로' '별로' '별로' '별로' '별로' '보통' '인기많음' '보통' '별로' '보통' '인기많음' '보통' '인기많음'
 '보통' '인기많음' '보통' '별로' '인기많음' '별로' '인기많음' '별로' '보통' '별로' '별로' '보통' '인기많음'
 '인기많음' '별로' '보통' '인기많음' '인기많음' '인기많음' '별로' '별로' '별로' '별로' '보통' '보통' '별로'
 '인기많음' '보통' '보통' '보통' '보통' '인기많음' '별로' '보통' '별로' '보통' '보통' '보통' '보통' '보통'
 '인기많음' '보통' '인기많음' '별로' '보통' '인기많음' '보통' '보통' '별로' '인기많음' '별로' '별로'
 '인기많음' '인기많음' '별로' '보통' '인기많음' '별로' '인기많음' '별로' '보통' '보통' '별로' '별로'
 '인기많음' '인기많음' '별로' '보통' '별로' '인기많음' '인기많음' '보통' '별로' '별로' '인기많음' '별로'
 '보통' '인기많음' '인기많음' '보통' '인기많음' '인기많음' '별로' '보통' '인기많음' '보통' '별로' '인기많음'
 '별로' '보통' '별로' '별로' '보통' '인기많음' '보통' '인기많음' '보통' '인기많음' '보통' '별로' '인기많음'

In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()
feature = mm.fit_transform(feature)

knc = KNeighborsClassifier(10)
knc.fit(feature, label)

NameError: name 'feature' is not defined

In [ ]:
airplane = float(input("비행기 : "))
game = float(input("게임 : "))
icecream = float(input("아이스크림 : "))

predictData = np.array([[airplane, game, icecream]])

result = knc.predict(predictData)[0]

print(result)

별로
